obj-$(CONFIG_EXYNOS_MEDIA_DEVICE)	+= mdev/
obj-$(CONFIG_VIDEO_EXYNOS_SCALER)	+= scaler/
obj-$(CONFIG_VIDEO_EXYNOS_MFC)		+= mfc/
obj-$(CONFIG_VIDEO_EXYNOS_HEVC)		+= hevc/
obj-$(CONFIG_VIDEO_EXYNOS_FIMG2D_V5)	+= fimg2d_v5/
obj-$(CONFIG_VIDEO_EXYNOS_SMFC)		+= smfc/
EXTRA_CLAGS += -Idrivers/media/video
